name: build

on:
  workflow_call:

jobs:
  build:
    uses: ./quarkus/quarkus-build.yml
    secrets: inherit
    with:
      push: true
  native:
    uses: ./quarkus/quarkus-build-native.yml
    secrets: inherit
    needs: [build]
    with:
      push: true